-- Table: public.account

-- DROP TABLE IF EXISTS public.account;

CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    account_firstname character varying COLLATE pg_catalog."default" NOT NULL,
    account_lastname character varying COLLATE pg_catalog."default" NOT NULL,
    account_email character varying COLLATE pg_catalog."default" NOT NULL,
    account_password character varying COLLATE pg_catalog."default" NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.account
    OWNER to admin;