-- Table: public.inventory

-- DROP TABLE IF EXISTS public.inventory;

CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inv_make character varying COLLATE pg_catalog."default" NOT NULL,
    inv_model character varying COLLATE pg_catalog."default" NOT NULL,
    inv_year character(4) COLLATE pg_catalog."default" NOT NULL,
    inv_description text COLLATE pg_catalog."default" NOT NULL,
    inv_image character varying COLLATE pg_catalog."default" NOT NULL,
    inv_thumbnail character varying COLLATE pg_catalog."default" NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying COLLATE pg_catalog."default" NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.inventory
    OWNER to admin;